// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZHHj3mtWRgpgkf-xtbn5A8ZIyK_Wu1n4',
    appId: '1:247578793772:web:a65e283771ade8fe68fe89',
    messagingSenderId: '247578793772',
    projectId: 'casebasedsimulation',
    authDomain: 'casebasedsimulation.firebaseapp.com',
    storageBucket: 'casebasedsimulation.appspot.com',
    measurementId: 'G-5SP8JZXTMY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC6aFAh5-qio5gs_PElVnV0YLLdVAVQsDk',
    appId: '1:247578793772:android:16d4cf51762510fc68fe89',
    messagingSenderId: '247578793772',
    projectId: 'casebasedsimulation',
    storageBucket: 'casebasedsimulation.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD_quvnJ21NJslxLpm2f7G6AGlDb0bt4pc',
    appId: '1:247578793772:ios:d9ffe8e76c693db268fe89',
    messagingSenderId: '247578793772',
    projectId: 'casebasedsimulation',
    storageBucket: 'casebasedsimulation.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD_quvnJ21NJslxLpm2f7G6AGlDb0bt4pc',
    appId: '1:247578793772:ios:7032aeaec5d0546368fe89',
    messagingSenderId: '247578793772',
    projectId: 'casebasedsimulation',
    storageBucket: 'casebasedsimulation.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
